log:
    path:     /
    defaults: { _controller: "LivnYouBundle:Log:index" }

log_details:
    path:     /{id}/details
    defaults: { _controller: "LivnYouBundle:Log:show" }

log_new:
    path:     /new
    defaults: { _controller: "LivnYouBundle:Log:new" }

log_create:
    path:     /create
    defaults: { _controller: "LivnYouBundle:Log:create" }
    methods:  POST

log_edit:
    path:     /{id}/edit
    defaults: { _controller: "LivnYouBundle:Log:edit" }

log_update:
    path:     /{id}/update
    defaults: { _controller: "LivnYouBundle:Log:update" }
    methods:  [POST, PUT]

log_delete:
    path:     /{id}/delete
    defaults: { _controller: "LivnYouBundle:Log:delete" }
    methods:  [POST, DELETE]
