pathology:
    path:     /
    defaults: { _controller: "LivnYouBundle:Pathology:index" }

pathology_details:
    path:     /{id}/details
    defaults: { _controller: "LivnYouBundle:Pathology:show" }

pathology_new:
    path:     /new
    defaults: { _controller: "LivnYouBundle:Pathology:new" }

pathology_create:
    path:     /create
    defaults: { _controller: "LivnYouBundle:Pathology:create" }
    methods:  POST

pathology_edit:
    path:     /{id}/edit
    defaults: { _controller: "LivnYouBundle:Pathology:edit" }

pathology_update:
    path:     /{id}/update
    defaults: { _controller: "LivnYouBundle:Pathology:update" }
    methods:  [POST, PUT]

pathology_delete:
    path:     /{id}/delete
    defaults: { _controller: "LivnYouBundle:Pathology:delete" }
    methods:  [POST, DELETE]
