physicalactivity:
    path:     /
    defaults: { _controller: "LivnYouBundle:PhysicalActivity:index" }

physicalactivity_details:
    path:     /{id}/details
    defaults: { _controller: "LivnYouBundle:PhysicalActivity:show" }

physicalactivity_new:
    path:     /new
    defaults: { _controller: "LivnYouBundle:PhysicalActivity:new" }

physicalactivity_create:
    path:     /create
    defaults: { _controller: "LivnYouBundle:PhysicalActivity:create" }
    methods:  POST

physicalactivity_edit:
    path:     /{id}/edit
    defaults: { _controller: "LivnYouBundle:PhysicalActivity:edit" }

physicalactivity_update:
    path:     /{id}/update
    defaults: { _controller: "LivnYouBundle:PhysicalActivity:update" }
    methods:  [POST, PUT]

physicalactivity_delete:
    path:     /{id}/delete
    defaults: { _controller: "LivnYouBundle:PhysicalActivity:delete" }
    methods:  [POST, DELETE]
