translationphysicalactivity:
    path:     /
    defaults: { _controller: "LivnYouBundle:TranslationPhysicalActivity:index" }

translationphysicalactivity_details:
    path:     /{id}/details
    defaults: { _controller: "LivnYouBundle:TranslationPhysicalActivity:show" }

translationphysicalactivity_new:
    path:     /new
    defaults: { _controller: "LivnYouBundle:TranslationPhysicalActivity:new" }

translationphysicalactivity_create:
    path:     /create
    defaults: { _controller: "LivnYouBundle:TranslationPhysicalActivity:create" }
    methods:  POST

translationphysicalactivity_edit:
    path:     /{id}/edit
    defaults: { _controller: "LivnYouBundle:TranslationPhysicalActivity:edit" }

translationphysicalactivity_update:
    path:     /{id}/update
    defaults: { _controller: "LivnYouBundle:TranslationPhysicalActivity:update" }
    methods:  [POST, PUT]

translationphysicalactivity_delete:
    path:     /{id}/delete
    defaults: { _controller: "LivnYouBundle:TranslationPhysicalActivity:delete" }
    methods:  [POST, DELETE]
