
security:
    access_control:
        - { path: ^/(en|fr)/api/mesurements$, methods: [GET], roles: [ROLE_USER] }
        - { path: ^/(en|fr)/api/mesurements$, methods: [POST], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr)/api/mesurements$, methods: [PUT, PATCH], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr|ar)/api/mesurements$, methods: [DELETE], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    #Security for settings resource
    #Languages
        - { path: ^/(en|fr)/api/languages, methods: [GET], roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/(en|fr)/api/languages, methods: [POST], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr)/api/languages, methods: [PUT, PATCH], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr)/api/languages, methods: [DELETE], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }

    #Countries
        - { path: ^/(en|fr)/api/countries, methods: [GET], roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/(en|fr)/api/countries, methods: [POST], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr)/api/countries, methods: [PUT, PATCH], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr)/api/countries, methods: [DELETE], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }

    #Pathologies
        - { path: ^/(en|fr)/api/pathologies, methods: [GET], roles: [ROLE_API] }
        - { path: ^/(en|fr)/api/pathologies, methods: [POST], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr)/api/pathologies, methods: [PUT, PATCH], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr)/api/pathologies, methods: [DELETE], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }

    #PhysicalActivities
        - { path: ^/(en|fr)/api/physicalactivities, methods: [GET], roles: [ROLE_API] }
        - { path: ^/(en|fr)/api/physicalactivities, methods: [POST], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr)/api/physicalactivities, methods: [PUT, PATCH], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr)/api/physicalactivities, methods: [DELETE], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }

    #Security for User resource
    #Users
        - { path: ^/(en|fr)/api/users, methods: [GET], roles: [ROLE_API] }
        - { path: ^/(en|fr)/api/users, methods: [POST], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr)/api/users, methods: [PUT, PATCH], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/(en|fr)/api/users, methods: [DELETE], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
