
security:
    access_control:
        - { path: ^/(en|fr|ar)/api/mesurements$, methods: [GET], roles: [ROLE_SUBSCRIBER] }
        - { path: ^/(en|fr|ar)/api/mesurements$, methods: [POST], roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
